import { useI18n } from "./i18n";

const UI_TEXT = {
  en: {
    disconnect: {
      lost: "Connection lost. Reconnecting…",
      retry: "Retry",
      retrying: "Retrying…",
      dismiss: "Dismiss",
    },
    receipts: {
      title: "Receipts",
      desc: "What each agent actually did, tool by tool. No claims — just the log.",
      loading: "Loading…",
      loadError: "Could not load receipts.",
      empty: "No receipts yet. Agents write one when they use a tool.",
      agent: "Agent",
      action: "Action",
      time: "Time",
      tokens: "Tokens",
      cost: "Cost",
      back: "Back to receipts",
      traceDesc: "Tool-by-tool trace of this task.",
      traceError: "Could not load task trace.",
      traceEmpty: "No tool calls in this task yet.",
      unknown: "(unknown)",
    },
    threads: {
      title: "Threads",
      active: (count: number) =>
        `${count} active thread${count === 1 ? "" : "s"}`,
      loading: "Loading threads…",
      empty: "No threads yet. Reply to a message to start one.",
      replies: (count: number) => `${count} repl${count === 1 ? "y" : "ies"}`,
      noContent: "(no content)",
    },
    wiki: {
      tabAria: "Wiki surfaces",
      tabs: { wiki: "Wiki", notebooks: "Notebooks", reviews: "Reviews" },
      pendingBadge: (count: number) => `${count} pending`,
      catalogTitle: "Project memory",
      statsArticles: (count: number) => `${count} articles`,
      statsAgentUpdates: (count: number) => `${count} agent updates`,
      catalogDesc:
        "Project goals, decisions, task history, and delivery notes that agents read before work.",
      newMemoryPage: "+ New memory page",
      history: "History",
      overviewAria: "Project memory overview",
      projectPages: "Project pages",
      projectPagesDesc:
        "Start from the project page when you need goals, constraints, and the latest task decisions.",
      projectPagesEmpty:
        "Create a project first; its memory page will appear here.",
      recentUpdates: "Recent updates",
      recentUpdatesDesc:
        "Use this to scan what changed before starting new work.",
      noMemoryPages: "No memory pages yet.",
      searchPlaceholder: "Search wiki…",
      viewHistory: "View history ->",
      checkHealth: "Check wiki health ->",
      newSection: "new",
      newSectionAria: "New section",
      schemaSectionTitle: "Declared in your blueprint",
      discoveredSectionTitle: "Discovered from articles your team has written",
      noArticles: "No articles yet",
      blueprintBanner: (slug: string) =>
        `"${slug}" is a new section your team built organically. Add it to your blueprint to make it permanent.`,
      dismissBanner: "Dismiss banner",
      articleLoading: "Loading article…",
      articleError: (message: string) => `Error: ${message}`,
      articleNotFound: "Article not found.",
      articleHatnote:
        "This article is auto-generated from team activity. See the commit history for the full trail.",
      articleHistoryPreparing:
        "Memory history for this page is being prepared.",
      articleStrapline:
        "Project memory for decisions, constraints, and delivery notes.",
      breadcrumbRoot: "Project memory",
      liveEditing: (name: string) =>
        `${name} is editing this article right now.`,
      lastEditedBy: "Last edited by",
      human: "Human",
      started: "started",
      by: "by",
      revisionsCount: (count: number) =>
        `${count} revision${count === 1 ? "" : "s"}`,
      articleViewsAria: "Article views",
      hatbar: {
        article: "Article",
        talk: "Talk",
        edit: "Edit source",
        history: "History",
        raw: "Raw markdown",
      },
      pageStats: "Page stats",
      revisions: "Revisions",
      contributors: "Contributors",
      contributorsValue: (count: number) => `${count} agents`,
      words: "Words",
      created: "Created",
      lastEdit: "Last edit",
      viewed: "Viewed",
      viewedValue: (count: number) => `${count} times`,
      sources: "Sources",
      loadingSources: "loading sources…",
      seeAlso: "See also",
      categoriesAria: "Categories",
      categories: "Categories:",
      citeThisPage: "Cite this page",
      copyWikilink: "Copy wikilink",
      copied: "copied",
      copy: "copy",
      citeHint: "Paste this in any article to link here.",
      footerActions: [
        "View memory history",
        "Copy page link",
        "Download markdown",
        "Export PDF",
      ],
      footerEdited: (date: string, author: string) =>
        `This article was last edited on ${date} by ${author}. Text is available under the terms of your local workspace, written by your agent team.`,
      footerAttribution: (path: string) =>
        `Changes to ${path} are attributed to the person or agent that saved them.`,
      live: "Live:",
      status: "Status:",
      revShort: (count: number) => `${count} rev`,
      contribShort: (count: number) => `${count} contrib`,
      wordsShort: (count: number) => `${count.toLocaleString()} words`,
      fullDate: (date: string, time: string) => `${date} at ${time} UTC`,
      auditTitle: "Memory history",
      auditDesc:
        "Every project memory update, newest first. Use this to check what changed, who changed it, and which pages were touched.",
      auditStatsLoading: "Loading…",
      auditStatsError: "Error",
      auditStatsLabel: (entries: number, authors: number, paths: number) =>
        `${entries} entries · ${authors} authors · ${paths} paths touched`,
      filtersAria: "Filters",
      author: "Author",
      all: "All",
      agentsOnly: "Agents only",
      systemOnly: "System (bootstrap + recovery + init)",
      search: "Search",
      auditSearchPlaceholder:
        "Match message or path (e.g. playbooks, renewal, sarah)",
      window: "Window",
      allTime: "All time",
      last24Hours: "Last 24 hours",
      last7Days: "Last 7 days",
      last30Days: "Last 30 days",
      last90Days: "Last 90 days",
      limit: "Limit",
      noLimit: "No limit",
      exportCsv: "Export CSV",
      loadingHistory: "Loading memory history…",
      noEdits: "No edits yet. Project memory updates will appear here.",
      noFilterMatches: "No entries match your filters.",
      when: "When",
      message: "Message",
      paths: "Paths",
      sha: "SHA",
      wikiHealthTitle: "Wiki health check",
      wikiHealthDesc:
        "A daily sweep of the whole wiki to surface things worth your attention: conflicting facts, pages with no links in or out, claims that may be out of date, entities that should probably be linked, and possible duplicates.",
      actionsAria: "Actions",
      checking: "Checking…",
      checkAgainNow: "Check again now",
      lastChecked: (date: string) => `Last checked: ${date}`,
      lintStatsLabel: (critical: number, warning: number, info: number) =>
        `${critical} need attention · ${warning} worth a look · ${info} FYI`,
      checkingWiki: "Checking the wiki…",
      allClear: "All clear. Nothing needs your attention right now.",
      priority: "Priority",
      issue: "Issue",
      page: "Page",
      whatsGoingOn: "What's going on",
      action: "Action",
      resolve: "Resolve",
      findingTitle: (label: string) => `${label} finding`,
      findingTypes: {
        contradictions: "Conflicting facts",
        orphans: "Page with no links",
        stale: "May be out of date",
        missing_crossrefs: "Should probably be linked",
        dedup_review: "Possible duplicate",
      },
      severities: {
        critical: "Needs attention",
        warning: "Worth a look",
        info: "FYI",
      },
      editorEmptyError: "Article content cannot be empty.",
      editorSaveFailed: "Save failed.",
      editorSummary: "Edit summary",
      editorSummaryPlaceholder: "human: short description of the edit",
      editorHelp: "Markdown is supported. [[slug]] links another memory page.",
      editorDraftFrom: (ago: string) => `Unsaved draft from ${ago}.`,
      restoreDraft: "Restore draft",
      discard: "Discard",
      conflictTitle: "Someone else edited this article.",
      conflictBody:
        "Your save was rejected because the article changed since you opened it.",
      reloadLatest: "Reload latest & re-apply",
      source: "Source",
      preview: "Preview",
      articleSource: (path: string) => `Article source (${path})`,
      livePreviewAria: "Live preview",
      saving: "Saving…",
      saveChanges: "Save changes",
      cancel: "Cancel",
      hidePreview: "Hide preview",
      momentsAgo: "moments ago",
      justNow: "just now",
      secondsAgo: (count: number) => `${count}s ago`,
      minutesAgo: (count: number) => `${count}m ago`,
      hoursAgo: (count: number) => `${count}h ago`,
      daysAgo: (count: number) => `${count}d ago`,
      monthsAgo: (count: number) =>
        `${count} month${count === 1 ? "" : "s"} ago`,
      yearsAgo: (count: number) => `${count} year${count === 1 ? "" : "s"} ago`,
      section: "Section",
      slug: "Slug",
      title: "Title",
      newWikiArticle: "New wiki article",
      newSectionOption: "+ New section…",
      titleRequired: "Title is required.",
      articleExists:
        "An article already exists at that path. Pick a different slug.",
      createArticleFailed: "Failed to create article.",
      newArticleStub: "Stub — write something useful here.",
      willCreate: (path: string) => `Will create ${path}`,
      creating: "Creating…",
      createArticle: "Create article",
      segmentRequired: (label: string) => `${label} is required.`,
      segmentCannotContain: (label: string, value: string) =>
        `${label} cannot contain "${value}".`,
      segmentSlugOnly: (label: string) =>
        `${label} must be lowercase letters, numbers, and hyphens only.`,
      resolveContradictionTitle: "Resolve contradiction",
      entity: "Entity",
      unknown: "(unknown)",
      facts: "facts",
      conflictingFactsAria: "Conflicting facts",
      factA: "Fact A",
      factB: "Fact B",
      both: "Both",
      resolveHelp:
        "Pick which fact is authoritative. The other will be marked superseded. Choose Both to keep both as non-contradictory.",
      resolving: "Resolving…",
      resolved: "Resolved.",
      resolvedCommit: (sha: string) => `Resolved. Commit ${sha}.`,
      resolveFailed: "Failed to resolve contradiction.",
      factsOnFile: "Facts on file",
      loadFactsFailed: "Failed to load facts",
      loadingFacts: "loading facts…",
      noFacts: "0 facts recorded yet. Agents will add facts as they work.",
      showRecentOnly: "show recent only",
      showAllMore: (count: number) => `show all (${count} more)`,
      reinforced: (date: string) => `reinforced ${date}`,
      supersedesPrior: (count: number) => `supersedes ${count} prior`,
      validRange: (from: string, until: string) => `valid ${from} -> ${until}`,
      validUntil: (until: string) => `valid until ${until}`,
      validFrom: (from: string) => `valid from ${from}`,
      related: "Related",
      relatedLoadFailed: "Failed to load related entities",
      loadingRelated: "loading related entities…",
      relatedEmpty:
        "No related entities yet. Wikilinks in recorded facts will connect this page to others.",
      occurrenceCount: "Occurrence count",
      briefLoadFailed: "Failed to load brief status",
      synthesisFailed: "Synthesis request failed",
      never: "never",
      newFactsSince: (count: number) =>
        `${count} new ${count === 1 ? "fact" : "facts"} since last synthesis`,
      briefSynthesized: (time: string) =>
        `Brief synthesized ${time}. 0 new facts since.`,
      synthesizing: "Synthesizing…",
      refreshBrief: "Refresh brief",
      compiledSkill: "Compiled skill:",
      compiledSkillPending: "Compiled skill pending — recompiling...",
      executionsLogged: (count: number) =>
        `${count} execution${count === 1 ? "" : "s"} logged`,
      executionLog: "Execution log",
      loadingExecutions: "loading executions…",
      noExecutions:
        "No executions recorded yet. Agents will log outcomes here as they run the playbook.",
      lastSynthesis: (time: string, count: number) =>
        `Last synthesis: ${time} · ${count} execution${count === 1 ? "" : "s"}`,
      noSynthesis:
        "No synthesis yet — learnings will be added after the first archivist run.",
      newExecutionsSince: (count: number) =>
        `${count} new execution${count === 1 ? "" : "s"} since last synthesis`,
      resynthesize: "Re-synthesize",
      synthesized: "Synthesized ✓",
      retrySynthesis: "Retry synthesis",
      liveWikiEditLog: "Live wiki edit log",
      justNowLower: "just now",
      referencedBy: "Referenced by",
      contents: "Contents",
      show: "show",
      hide: "hide",
      citedAnswerLoadingAria: "Loading cited answer…",
      searchingWiki: "Searching the wiki…",
      wikiLookupFailed: "Wiki lookup failed:",
      fromTheWiki: "From the wiki",
      partialMatch: " (partial match)",
      noMatch: " (no match)",
      outOfScope:
        "I can help with questions about people, companies, and activities in your workspace.",
      lastUpdated: (date: string) => `Last updated: ${date}`,
      sourceCount: (count: number) =>
        `${count} ${count === 1 ? "source" : "sources"}`,
      pamAria: "Pam the Archivist",
      pamTitle: "Pam - click for options",
      pamActionsAria: "Pam's actions",
      pamMenuHeader: "Pam can help with",
      pamMenuLoadFailed: "Could not load Pam's menu.",
      pamMenuLoading: "Loading…",
      pamNoActions: "No actions available.",
      pamOpenArticle: "Open an article to use Pam.",
      pamStartFailed: "Pam could not start.",
      pamFinishFailed: "Pam could not finish.",
      pamRunning: (label: string) => `Pam is working: ${label}...`,
      pamDone: (label: string) => `Done: ${label}`,
      pamFailed: (message: string) => `Pam: ${message}`,
    },
  },
  ko: {
    disconnect: {
      lost: "연결이 끊겼습니다. 다시 연결하는 중...",
      retry: "다시 시도",
      retrying: "다시 시도 중...",
      dismiss: "닫기",
    },
    receipts: {
      title: "영수증",
      desc: "각 에이전트가 실제로 어떤 도구를 썼는지 기록합니다. 주장보다 실행 로그를 보여줍니다.",
      loading: "불러오는 중...",
      loadError: "영수증을 불러오지 못했습니다.",
      empty: "아직 영수증이 없습니다. 에이전트가 도구를 사용하면 기록됩니다.",
      agent: "에이전트",
      action: "작업",
      time: "시간",
      tokens: "토큰",
      cost: "비용",
      back: "영수증 목록으로",
      traceDesc: "이 작업의 도구 실행 기록입니다.",
      traceError: "작업 실행 기록을 불러오지 못했습니다.",
      traceEmpty: "아직 이 작업의 도구 호출이 없습니다.",
      unknown: "(알 수 없음)",
    },
    threads: {
      title: "스레드",
      active: (count: number) => `활성 스레드 ${count}개`,
      loading: "스레드를 불러오는 중...",
      empty: "아직 스레드가 없습니다. 메시지에 답글을 달면 시작됩니다.",
      replies: (count: number) => `답글 ${count}개`,
      noContent: "(내용 없음)",
    },
    wiki: {
      tabAria: "위키 화면",
      tabs: { wiki: "위키", notebooks: "노트북", reviews: "검토" },
      pendingBadge: (count: number) => `대기 ${count}개`,
      catalogTitle: "프로젝트 메모리",
      statsArticles: (count: number) => `문서 ${count}개`,
      statsAgentUpdates: (count: number) => `에이전트 업데이트 ${count}개`,
      catalogDesc:
        "프로젝트 목표, 결정, 작업 이력, 전달 메모처럼 에이전트가 작업 전에 읽는 지식입니다.",
      newMemoryPage: "+ 새 메모리 페이지",
      history: "히스토리",
      overviewAria: "프로젝트 메모리 개요",
      projectPages: "프로젝트 페이지",
      projectPagesDesc:
        "목표, 제약, 최근 작업 결정을 확인할 때 프로젝트 페이지부터 보세요.",
      projectPagesEmpty:
        "프로젝트를 먼저 만들면 이곳에 메모리 페이지가 표시됩니다.",
      recentUpdates: "최근 업데이트",
      recentUpdatesDesc: "새 작업을 시작하기 전에 무엇이 바뀌었는지 봅니다.",
      noMemoryPages: "아직 메모리 페이지가 없습니다.",
      searchPlaceholder: "위키 검색...",
      viewHistory: "히스토리 보기 ->",
      checkHealth: "위키 상태 점검 ->",
      newSection: "새 항목",
      newSectionAria: "새 섹션",
      schemaSectionTitle: "블루프린트에 등록된 섹션",
      discoveredSectionTitle: "팀이 작성한 문서에서 발견된 섹션",
      noArticles: "아직 문서가 없습니다",
      blueprintBanner: (slug: string) =>
        `"${slug}" 섹션은 팀 문서에서 새로 발견되었습니다. 계속 쓸 섹션이면 블루프린트에 추가하세요.`,
      dismissBanner: "배너 닫기",
      articleLoading: "문서를 불러오는 중...",
      articleError: (message: string) => `오류: ${message}`,
      articleNotFound: "문서를 찾을 수 없습니다.",
      articleHatnote:
        "이 문서는 팀 활동을 바탕으로 자동 생성되었습니다. 전체 기록은 커밋 히스토리에서 확인할 수 있습니다.",
      articleHistoryPreparing:
        "이 페이지의 메모리 히스토리를 준비하는 중입니다.",
      articleStrapline:
        "결정, 제약, 전달 메모를 모아 둔 프로젝트 메모리입니다.",
      breadcrumbRoot: "프로젝트 메모리",
      liveEditing: (name: string) => `${name}가 지금 이 문서를 수정 중입니다.`,
      lastEditedBy: "마지막 수정",
      human: "사용자",
      started: "시작",
      by: "작성자",
      revisionsCount: (count: number) => `수정 ${count}회`,
      articleViewsAria: "문서 보기 방식",
      hatbar: {
        article: "문서",
        talk: "토론",
        edit: "원문 수정",
        history: "히스토리",
        raw: "마크다운 원문",
      },
      pageStats: "페이지 통계",
      revisions: "수정 횟수",
      contributors: "작성자",
      contributorsValue: (count: number) => `에이전트 ${count}명`,
      words: "단어 수",
      created: "생성일",
      lastEdit: "마지막 수정",
      viewed: "조회",
      viewedValue: (count: number) => `${count}회`,
      sources: "출처",
      loadingSources: "출처를 불러오는 중...",
      seeAlso: "같이 보기",
      categoriesAria: "카테고리",
      categories: "카테고리:",
      citeThisPage: "이 페이지 인용",
      copyWikilink: "위키링크 복사",
      copied: "복사됨",
      copy: "복사",
      citeHint: "다른 문서에서 이 페이지를 연결할 때 붙여넣으세요.",
      footerActions: [
        "메모리 히스토리 보기",
        "페이지 링크 복사",
        "마크다운 다운로드",
        "PDF 내보내기",
      ],
      footerEdited: (date: string, author: string) =>
        `이 문서는 ${date}에 ${author}가 마지막으로 수정했습니다. 내용은 로컬 워크스페이스 조건에 따라 사용할 수 있으며, 에이전트 팀이 작성했습니다.`,
      footerAttribution: (path: string) =>
        `${path}의 변경 사항은 저장한 사람 또는 에이전트에게 귀속됩니다.`,
      live: "실시간:",
      status: "상태:",
      revShort: (count: number) => `수정 ${count}회`,
      contribShort: (count: number) => `작성자 ${count}명`,
      wordsShort: (count: number) => `단어 ${count.toLocaleString()}개`,
      fullDate: (date: string, time: string) => `${date} ${time} UTC`,
      auditTitle: "메모리 히스토리",
      auditDesc:
        "프로젝트 메모리 업데이트를 최신순으로 보여줍니다. 무엇이 바뀌었고, 누가 바꿨고, 어떤 페이지가 영향을 받았는지 확인할 수 있습니다.",
      auditStatsLoading: "불러오는 중...",
      auditStatsError: "오류",
      auditStatsLabel: (entries: number, authors: number, paths: number) =>
        `기록 ${entries}개 · 작성자 ${authors}명 · 변경 경로 ${paths}개`,
      filtersAria: "필터",
      author: "작성자",
      all: "전체",
      agentsOnly: "에이전트만",
      systemOnly: "시스템(초기 설정 + 복구 + 초기화)",
      search: "검색",
      auditSearchPlaceholder:
        "메시지나 경로로 찾기 (예: playbooks, renewal, sarah)",
      window: "기간",
      allTime: "전체 기간",
      last24Hours: "최근 24시간",
      last7Days: "최근 7일",
      last30Days: "최근 30일",
      last90Days: "최근 90일",
      limit: "표시 개수",
      noLimit: "제한 없음",
      exportCsv: "CSV 내보내기",
      loadingHistory: "메모리 히스토리를 불러오는 중...",
      noEdits:
        "아직 수정 기록이 없습니다. 프로젝트 메모리가 업데이트되면 여기에 표시됩니다.",
      noFilterMatches: "필터와 일치하는 기록이 없습니다.",
      when: "시간",
      message: "메시지",
      paths: "경로",
      sha: "SHA",
      wikiHealthTitle: "위키 상태 점검",
      wikiHealthDesc:
        "위키 전체를 훑어 확인이 필요한 항목을 보여줍니다. 충돌하는 사실, 연결이 없는 페이지, 오래된 주장, 연결해야 할 엔티티, 중복 가능성을 찾습니다.",
      actionsAria: "작업",
      checking: "점검 중...",
      checkAgainNow: "지금 다시 점검",
      lastChecked: (date: string) => `마지막 점검: ${date}`,
      lintStatsLabel: (critical: number, warning: number, info: number) =>
        `확인 필요 ${critical}개 · 검토 권장 ${warning}개 · 참고 ${info}개`,
      checkingWiki: "위키를 점검하는 중...",
      allClear: "문제 없습니다. 지금 확인할 항목이 없습니다.",
      priority: "우선순위",
      issue: "문제",
      page: "페이지",
      whatsGoingOn: "상황",
      action: "작업",
      resolve: "해결",
      findingTitle: (label: string) => `${label} 항목`,
      findingTypes: {
        contradictions: "충돌하는 사실",
        orphans: "연결이 없는 페이지",
        stale: "오래되었을 수 있음",
        missing_crossrefs: "연결이 필요해 보임",
        dedup_review: "중복 가능성",
      },
      severities: {
        critical: "확인 필요",
        warning: "검토 권장",
        info: "참고",
      },
      editorEmptyError: "문서 내용을 비울 수 없습니다.",
      editorSaveFailed: "저장하지 못했습니다.",
      editorSummary: "수정 요약",
      editorSummaryPlaceholder: "human: 수정 내용을 짧게 설명",
      editorHelp:
        "마크다운을 사용할 수 있습니다. [[slug]] 형식으로 다른 메모리 페이지를 연결합니다.",
      editorDraftFrom: (ago: string) => `${ago}에 저장된 임시 초안이 있습니다.`,
      restoreDraft: "초안 복원",
      discard: "버리기",
      conflictTitle: "다른 사람이 이 문서를 수정했습니다.",
      conflictBody: "문서를 연 뒤 내용이 바뀌어서 저장이 거절되었습니다.",
      reloadLatest: "최신 내용 불러와 다시 적용",
      source: "원문",
      preview: "미리보기",
      articleSource: (path: string) => `문서 원문 (${path})`,
      livePreviewAria: "실시간 미리보기",
      saving: "저장 중...",
      saveChanges: "변경사항 저장",
      cancel: "취소",
      hidePreview: "미리보기 숨기기",
      momentsAgo: "방금 전",
      justNow: "방금",
      secondsAgo: (count: number) => `${count}초 전`,
      minutesAgo: (count: number) => `${count}분 전`,
      hoursAgo: (count: number) => `${count}시간 전`,
      daysAgo: (count: number) => `${count}일 전`,
      monthsAgo: (count: number) => `${count}개월 전`,
      yearsAgo: (count: number) => `${count}년 전`,
      section: "섹션",
      slug: "슬러그",
      title: "제목",
      newWikiArticle: "새 위키 문서",
      newSectionOption: "+ 새 섹션...",
      titleRequired: "제목을 입력하세요.",
      articleExists:
        "이미 같은 경로에 문서가 있습니다. 다른 슬러그를 입력하세요.",
      createArticleFailed: "문서를 만들지 못했습니다.",
      newArticleStub: "초안입니다. 여기에 필요한 내용을 작성하세요.",
      willCreate: (path: string) => `${path} 문서를 만듭니다`,
      creating: "생성 중...",
      createArticle: "문서 만들기",
      segmentRequired: (label: string) => `${label}을 입력하세요.`,
      segmentCannotContain: (label: string, value: string) =>
        `${label}에는 "${value}"를 넣을 수 없습니다.`,
      segmentSlugOnly: (label: string) =>
        `${label}은 영문 소문자, 숫자, 하이픈만 사용할 수 있습니다.`,
      resolveContradictionTitle: "충돌 해결",
      entity: "엔티티",
      unknown: "(알 수 없음)",
      facts: "사실",
      conflictingFactsAria: "충돌하는 사실",
      factA: "사실 A",
      factB: "사실 B",
      both: "둘 다",
      resolveHelp:
        "어떤 사실을 기준으로 삼을지 선택하세요. 다른 사실은 대체된 것으로 표시됩니다. 둘 다 맞다면 둘 다를 선택하세요.",
      resolving: "해결 중...",
      resolved: "해결했습니다.",
      resolvedCommit: (sha: string) => `해결했습니다. 커밋 ${sha}.`,
      resolveFailed: "충돌을 해결하지 못했습니다.",
      factsOnFile: "기록된 사실",
      loadFactsFailed: "사실을 불러오지 못했습니다.",
      loadingFacts: "사실을 불러오는 중...",
      noFacts:
        "아직 기록된 사실이 없습니다. 에이전트가 작업하면서 사실을 추가합니다.",
      showRecentOnly: "최근 항목만 보기",
      showAllMore: (count: number) => `전체 보기 (${count}개 더)`,
      reinforced: (date: string) => `${date}에 보강됨`,
      supersedesPrior: (count: number) => `이전 사실 ${count}개를 대체`,
      validRange: (from: string, until: string) =>
        `유효 기간 ${from} -> ${until}`,
      validUntil: (until: string) => `${until}까지 유효`,
      validFrom: (from: string) => `${from}부터 유효`,
      related: "관련 항목",
      relatedLoadFailed: "관련 항목을 불러오지 못했습니다.",
      loadingRelated: "관련 항목을 불러오는 중...",
      relatedEmpty:
        "아직 관련 항목이 없습니다. 기록된 사실에 위키링크가 있으면 다른 페이지와 연결됩니다.",
      occurrenceCount: "등장 횟수",
      briefLoadFailed: "요약 상태를 불러오지 못했습니다.",
      synthesisFailed: "요약 생성을 요청하지 못했습니다.",
      never: "없음",
      newFactsSince: (count: number) => `마지막 요약 이후 새 사실 ${count}개`,
      briefSynthesized: (time: string) =>
        `요약 생성: ${time}. 이후 새 사실 0개.`,
      synthesizing: "요약 생성 중...",
      refreshBrief: "요약 새로 만들기",
      compiledSkill: "컴파일된 스킬:",
      compiledSkillPending: "컴파일된 스킬 대기 중 — 다시 컴파일하는 중...",
      executionsLogged: (count: number) => `실행 기록 ${count}회`,
      executionLog: "실행 기록",
      loadingExecutions: "실행 기록을 불러오는 중...",
      noExecutions:
        "아직 실행 기록이 없습니다. 에이전트가 플레이북을 실행하면 결과가 여기에 기록됩니다.",
      lastSynthesis: (time: string, count: number) =>
        `마지막 요약: ${time} · 실행 ${count}회`,
      noSynthesis:
        "아직 요약이 없습니다. 첫 아카이비스트 실행 후 배운 내용이 추가됩니다.",
      newExecutionsSince: (count: number) =>
        `마지막 요약 이후 새 실행 ${count}회`,
      resynthesize: "다시 요약",
      synthesized: "요약 완료 ✓",
      retrySynthesis: "요약 다시 시도",
      liveWikiEditLog: "실시간 위키 수정 기록",
      justNowLower: "방금",
      referencedBy: "이 문서를 참조함",
      contents: "목차",
      show: "보기",
      hide: "숨기기",
      citedAnswerLoadingAria: "인용 답변을 불러오는 중...",
      searchingWiki: "위키를 검색하는 중...",
      wikiLookupFailed: "위키 조회 실패:",
      fromTheWiki: "위키에서 가져옴",
      partialMatch: " (일부 일치)",
      noMatch: " (일치 없음)",
      outOfScope:
        "워크스페이스 안의 사람, 회사, 활동에 관한 질문에 답할 수 있습니다.",
      lastUpdated: (date: string) => `마지막 업데이트: ${date}`,
      sourceCount: (count: number) => `출처 ${count}개`,
      pamAria: "아카이비스트 Pam",
      pamTitle: "Pam - 옵션 보기",
      pamActionsAria: "Pam 작업",
      pamMenuHeader: "Pam이 도울 수 있는 일",
      pamMenuLoadFailed: "Pam 메뉴를 불러오지 못했습니다.",
      pamMenuLoading: "불러오는 중...",
      pamNoActions: "사용할 수 있는 작업이 없습니다.",
      pamOpenArticle: "Pam을 사용하려면 문서를 열어주세요.",
      pamStartFailed: "Pam을 시작하지 못했습니다.",
      pamFinishFailed: "Pam이 작업을 끝내지 못했습니다.",
      pamRunning: (label: string) => `Pam 작업 중: ${label}...`,
      pamDone: (label: string) => `완료: ${label}`,
      pamFailed: (message: string) => `Pam: ${message}`,
    },
  },
} as const;

export function useUiText() {
  const { language } = useI18n();
  return UI_TEXT[language] ?? UI_TEXT.en;
}
